version: "3.9"

services:

  backend:
    build:
      context: ./backend
    container_name: lead-backend
    ports:
      - "8001:8001"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: lead-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://192.168.1.5:8001/api/v1
    depends_on:
      - backend
    restart: unless-stopped